// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `AGMExecutiveTopic.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <AGMExecutiveTopic.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <Ice/LocalException.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_ids[2] =
{
    "::Ice::Object",
    "::RoboCompAGMExecutiveTopic::AGMExecutiveTopic"
};
const ::std::string iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_ops[] =
{
    "edgeUpdated",
    "edgesUpdated",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "structuralChange",
    "symbolUpdated",
    "symbolsUpdated"
};
const ::std::string iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_structuralChange_name = "structuralChange";
const ::std::string iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_symbolUpdated_name = "symbolUpdated";
const ::std::string iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_symbolsUpdated_name = "symbolsUpdated";
const ::std::string iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_edgeUpdated_name = "edgeUpdated";
const ::std::string iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_edgesUpdated_name = "edgesUpdated";

}

bool
RoboCompAGMExecutiveTopic::AGMExecutiveTopic::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_ids, iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_ids + 2, s);
}

::std::vector<::std::string>
RoboCompAGMExecutiveTopic::AGMExecutiveTopic::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_ids[0], &iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_ids[2]);
}

::std::string
RoboCompAGMExecutiveTopic::AGMExecutiveTopic::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompAGMExecutiveTopic::AGMExecutiveTopic::ice_staticId()
{
    static const ::std::string typeId = "::RoboCompAGMExecutiveTopic::AGMExecutiveTopic";
    return typeId;
}

bool
RoboCompAGMExecutiveTopic::AGMExecutiveTopic::_iceD_structuralChange(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::RoboCompAGMWorldModel::World iceP_w;
    istr->readAll(iceP_w);
    inS.endReadParams();
    this->structuralChange(::std::move(iceP_w), current);
    inS.writeEmptyParams();
    return true;
}

bool
RoboCompAGMExecutiveTopic::AGMExecutiveTopic::_iceD_symbolUpdated(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::RoboCompAGMWorldModel::Node iceP_modification;
    istr->readAll(iceP_modification);
    inS.endReadParams();
    this->symbolUpdated(::std::move(iceP_modification), current);
    inS.writeEmptyParams();
    return true;
}

bool
RoboCompAGMExecutiveTopic::AGMExecutiveTopic::_iceD_symbolsUpdated(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::RoboCompAGMWorldModel::NodeSequence iceP_modifications;
    istr->readAll(iceP_modifications);
    inS.endReadParams();
    this->symbolsUpdated(::std::move(iceP_modifications), current);
    inS.writeEmptyParams();
    return true;
}

bool
RoboCompAGMExecutiveTopic::AGMExecutiveTopic::_iceD_edgeUpdated(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::RoboCompAGMWorldModel::Edge iceP_modification;
    istr->readAll(iceP_modification);
    inS.endReadParams();
    this->edgeUpdated(::std::move(iceP_modification), current);
    inS.writeEmptyParams();
    return true;
}

bool
RoboCompAGMExecutiveTopic::AGMExecutiveTopic::_iceD_edgesUpdated(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::RoboCompAGMWorldModel::EdgeSequence iceP_modifications;
    istr->readAll(iceP_modifications);
    inS.endReadParams();
    this->edgesUpdated(::std::move(iceP_modifications), current);
    inS.writeEmptyParams();
    return true;
}

bool
RoboCompAGMExecutiveTopic::AGMExecutiveTopic::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_ops, iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_ops + 9, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_ops)
    {
        case 0:
        {
            return _iceD_edgeUpdated(in, current);
        }
        case 1:
        {
            return _iceD_edgesUpdated(in, current);
        }
        case 2:
        {
            return _iceD_ice_id(in, current);
        }
        case 3:
        {
            return _iceD_ice_ids(in, current);
        }
        case 4:
        {
            return _iceD_ice_isA(in, current);
        }
        case 5:
        {
            return _iceD_ice_ping(in, current);
        }
        case 6:
        {
            return _iceD_structuralChange(in, current);
        }
        case 7:
        {
            return _iceD_symbolUpdated(in, current);
        }
        case 8:
        {
            return _iceD_symbolsUpdated(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}

void
RoboCompAGMExecutiveTopic::AGMExecutiveTopicPrx::_iceI_structuralChange(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::RoboCompAGMWorldModel::World& iceP_w, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_structuralChange_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_w);
        },
        nullptr);
}

void
RoboCompAGMExecutiveTopic::AGMExecutiveTopicPrx::_iceI_symbolUpdated(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::RoboCompAGMWorldModel::Node& iceP_modification, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_symbolUpdated_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_modification);
        },
        nullptr);
}

void
RoboCompAGMExecutiveTopic::AGMExecutiveTopicPrx::_iceI_symbolsUpdated(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::RoboCompAGMWorldModel::NodeSequence& iceP_modifications, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_symbolsUpdated_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_modifications);
        },
        nullptr);
}

void
RoboCompAGMExecutiveTopic::AGMExecutiveTopicPrx::_iceI_edgeUpdated(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::RoboCompAGMWorldModel::Edge& iceP_modification, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_edgeUpdated_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_modification);
        },
        nullptr);
}

void
RoboCompAGMExecutiveTopic::AGMExecutiveTopicPrx::_iceI_edgesUpdated(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::RoboCompAGMWorldModel::EdgeSequence& iceP_modifications, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_edgesUpdated_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_modifications);
        },
        nullptr);
}

::std::shared_ptr<::Ice::ObjectPrx>
RoboCompAGMExecutiveTopic::AGMExecutiveTopicPrx::_newInstance() const
{
    return ::IceInternal::createProxy<AGMExecutiveTopicPrx>();
}

const ::std::string&
RoboCompAGMExecutiveTopic::AGMExecutiveTopicPrx::ice_staticId()
{
    return RoboCompAGMExecutiveTopic::AGMExecutiveTopic::ice_staticId();
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_structuralChange_name = "structuralChange";

const ::std::string iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_symbolUpdated_name = "symbolUpdated";

const ::std::string iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_symbolsUpdated_name = "symbolsUpdated";

const ::std::string iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_edgeUpdated_name = "edgeUpdated";

const ::std::string iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_edgesUpdated_name = "edgesUpdated";

}
::IceProxy::Ice::Object* ::IceProxy::RoboCompAGMExecutiveTopic::upCast(::IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic* p) { return p; }

void
::IceProxy::RoboCompAGMExecutiveTopic::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic;
        v->_copyFrom(proxy);
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::_iceI_begin_structuralChange(const ::RoboCompAGMWorldModel::World& iceP_w, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_structuralChange_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_structuralChange_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_w);
        result->endWriteParams();
        result->invoke(iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_structuralChange_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::end_structuralChange(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_structuralChange_name);
}

::Ice::AsyncResultPtr
IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::_iceI_begin_symbolUpdated(const ::RoboCompAGMWorldModel::Node& iceP_modification, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_symbolUpdated_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_symbolUpdated_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_modification);
        result->endWriteParams();
        result->invoke(iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_symbolUpdated_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::end_symbolUpdated(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_symbolUpdated_name);
}

::Ice::AsyncResultPtr
IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::_iceI_begin_symbolsUpdated(const ::RoboCompAGMWorldModel::NodeSequence& iceP_modifications, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_symbolsUpdated_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_symbolsUpdated_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_modifications);
        result->endWriteParams();
        result->invoke(iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_symbolsUpdated_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::end_symbolsUpdated(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_symbolsUpdated_name);
}

::Ice::AsyncResultPtr
IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::_iceI_begin_edgeUpdated(const ::RoboCompAGMWorldModel::Edge& iceP_modification, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_edgeUpdated_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_edgeUpdated_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_modification);
        result->endWriteParams();
        result->invoke(iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_edgeUpdated_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::end_edgeUpdated(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_edgeUpdated_name);
}

::Ice::AsyncResultPtr
IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::_iceI_begin_edgesUpdated(const ::RoboCompAGMWorldModel::EdgeSequence& iceP_modifications, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_edgesUpdated_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_edgesUpdated_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_modifications);
        result->endWriteParams();
        result->invoke(iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_edgesUpdated_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::end_edgesUpdated(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_edgesUpdated_name);
}

::IceProxy::Ice::Object*
IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::_newInstance() const
{
    return new AGMExecutiveTopic;
}

const ::std::string&
IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::ice_staticId()
{
    return ::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::ice_staticId();
}

RoboCompAGMExecutiveTopic::AGMExecutiveTopic::~AGMExecutiveTopic()
{
}

::Ice::Object* RoboCompAGMExecutiveTopic::upCast(::RoboCompAGMExecutiveTopic::AGMExecutiveTopic* p) { return p; }


namespace
{
const ::std::string iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_ids[2] =
{
    "::Ice::Object",
    "::RoboCompAGMExecutiveTopic::AGMExecutiveTopic"
};

}

bool
RoboCompAGMExecutiveTopic::AGMExecutiveTopic::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_ids, iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_ids + 2, s);
}

::std::vector< ::std::string>
RoboCompAGMExecutiveTopic::AGMExecutiveTopic::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_ids[0], &iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_ids[2]);
}

const ::std::string&
RoboCompAGMExecutiveTopic::AGMExecutiveTopic::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompAGMExecutiveTopic::AGMExecutiveTopic::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::RoboCompAGMExecutiveTopic::AGMExecutiveTopic";
    return typeId;
#else
    return iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_ids[1];
#endif
}

bool
RoboCompAGMExecutiveTopic::AGMExecutiveTopic::_iceD_structuralChange(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::RoboCompAGMWorldModel::World iceP_w;
    istr->read(iceP_w);
    inS.endReadParams();
    this->structuralChange(iceP_w, current);
    inS.writeEmptyParams();
    return true;
}

bool
RoboCompAGMExecutiveTopic::AGMExecutiveTopic::_iceD_symbolUpdated(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::RoboCompAGMWorldModel::Node iceP_modification;
    istr->read(iceP_modification);
    inS.endReadParams();
    this->symbolUpdated(iceP_modification, current);
    inS.writeEmptyParams();
    return true;
}

bool
RoboCompAGMExecutiveTopic::AGMExecutiveTopic::_iceD_symbolsUpdated(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::RoboCompAGMWorldModel::NodeSequence iceP_modifications;
    istr->read(iceP_modifications);
    inS.endReadParams();
    this->symbolsUpdated(iceP_modifications, current);
    inS.writeEmptyParams();
    return true;
}

bool
RoboCompAGMExecutiveTopic::AGMExecutiveTopic::_iceD_edgeUpdated(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::RoboCompAGMWorldModel::Edge iceP_modification;
    istr->read(iceP_modification);
    inS.endReadParams();
    this->edgeUpdated(iceP_modification, current);
    inS.writeEmptyParams();
    return true;
}

bool
RoboCompAGMExecutiveTopic::AGMExecutiveTopic::_iceD_edgesUpdated(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::RoboCompAGMWorldModel::EdgeSequence iceP_modifications;
    istr->read(iceP_modifications);
    inS.endReadParams();
    this->edgesUpdated(iceP_modifications, current);
    inS.writeEmptyParams();
    return true;
}

namespace
{
const ::std::string iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_all[] =
{
    "edgeUpdated",
    "edgesUpdated",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "structuralChange",
    "symbolUpdated",
    "symbolsUpdated"
};

}

bool
RoboCompAGMExecutiveTopic::AGMExecutiveTopic::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_all, iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_all + 9, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompAGMExecutiveTopic_AGMExecutiveTopic_all)
    {
        case 0:
        {
            return _iceD_edgeUpdated(in, current);
        }
        case 1:
        {
            return _iceD_edgesUpdated(in, current);
        }
        case 2:
        {
            return _iceD_ice_id(in, current);
        }
        case 3:
        {
            return _iceD_ice_ids(in, current);
        }
        case 4:
        {
            return _iceD_ice_isA(in, current);
        }
        case 5:
        {
            return _iceD_ice_ping(in, current);
        }
        case 6:
        {
            return _iceD_structuralChange(in, current);
        }
        case 7:
        {
            return _iceD_symbolUpdated(in, current);
        }
        case 8:
        {
            return _iceD_symbolsUpdated(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}

void
RoboCompAGMExecutiveTopic::AGMExecutiveTopic::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    Ice::StreamWriter< ::RoboCompAGMExecutiveTopic::AGMExecutiveTopic, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
RoboCompAGMExecutiveTopic::AGMExecutiveTopic::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    Ice::StreamReader< ::RoboCompAGMExecutiveTopic::AGMExecutiveTopic, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}

void
RoboCompAGMExecutiveTopic::_icePatchObjectPtr(AGMExecutiveTopicPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::RoboCompAGMExecutiveTopic::AGMExecutiveTopicPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::ice_staticId(), v);
    }
}

namespace Ice
{
}

#endif
