//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `AGMExecutiveTopic.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __AGMExecutiveTopic_h__
#define __AGMExecutiveTopic_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/ValueF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Comparable.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/GCObject.h>
#include <Ice/Value.h>
#include <Ice/Incoming.h>
#include <Ice/FactoryTableInit.h>
#include <IceUtil/ScopedArray.h>
#include <Ice/Optional.h>
#include <Ice/ExceptionHelpers.h>
#include <AGMWorldModel.h>
#include <Planning.h>
#include <AGMExecutive.h>
#include <IceUtil/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 3
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace RoboCompAGMExecutiveTopic
{

class AGMExecutiveTopic;
class AGMExecutiveTopicPrx;

}

namespace RoboCompAGMExecutiveTopic
{

class AGMExecutiveTopic : public virtual ::Ice::Object
{
public:

    using ProxyType = AGMExecutiveTopicPrx;

    /**
     * Determines whether this object supports an interface with the given Slice type ID.
     * @param id The fully-scoped Slice type ID.
     * @param current The Current object for the invocation.
     * @return True if this object supports the interface, false, otherwise.
     */
    virtual bool ice_isA(::std::string id, const ::Ice::Current& current) const override;

    /**
     * Obtains a list of the Slice type IDs representing the interfaces supported by this object.
     * @param current The Current object for the invocation.
     * @return A list of fully-scoped type IDs.
     */
    virtual ::std::vector<::std::string> ice_ids(const ::Ice::Current& current) const override;

    /**
     * Obtains a Slice type ID representing the most-derived interface supported by this object.
     * @param current The Current object for the invocation.
     * @return A fully-scoped type ID.
     */
    virtual ::std::string ice_id(const ::Ice::Current& current) const override;

    /**
     * Obtains the Slice type ID corresponding to this class.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

    virtual void edgeUpdated(::RoboCompAGMWorldModel::Edge modification, const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_edgeUpdated(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual void edgesUpdated(::RoboCompAGMWorldModel::EdgeSequence modifications, const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_edgesUpdated(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual void selfEdgeAdded(int nodeid, ::std::string edgeType, ::RoboCompAGMWorldModel::StringDictionary attributes, const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_selfEdgeAdded(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual void selfEdgeDeleted(int nodeid, ::std::string edgeType, const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_selfEdgeDeleted(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual void structuralChange(::RoboCompAGMWorldModel::World w, const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_structuralChange(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual void symbolUpdated(::RoboCompAGMWorldModel::Node modification, const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_symbolUpdated(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual void symbolsUpdated(::RoboCompAGMWorldModel::NodeSequence modifications, const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_symbolsUpdated(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    /// \cond INTERNAL
    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&) override;
    /// \endcond
};

}

namespace RoboCompAGMExecutiveTopic
{

class AGMExecutiveTopicPrx : public virtual ::Ice::Proxy<AGMExecutiveTopicPrx, ::Ice::ObjectPrx>
{
public:

    void edgeUpdated(const ::RoboCompAGMWorldModel::Edge& modification, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        _makePromiseOutgoing<void>(true, this, &AGMExecutiveTopicPrx::_iceI_edgeUpdated, modification, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto edgeUpdatedAsync(const ::RoboCompAGMWorldModel::Edge& modification, const ::Ice::Context& context = ::Ice::noExplicitContext)
        -> decltype(::std::declval<P<void>>().get_future())
    {
        return _makePromiseOutgoing<void, P>(false, this, &AGMExecutiveTopicPrx::_iceI_edgeUpdated, modification, context);
    }

    ::std::function<void()>
    edgeUpdatedAsync(const ::RoboCompAGMWorldModel::Edge& modification,
                     ::std::function<void()> response,
                     ::std::function<void(::std::exception_ptr)> ex = nullptr,
                     ::std::function<void(bool)> sent = nullptr,
                     const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<void>(response, ex, sent, this, &RoboCompAGMExecutiveTopic::AGMExecutiveTopicPrx::_iceI_edgeUpdated, modification, context);
    }

    /// \cond INTERNAL
    void _iceI_edgeUpdated(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>&, const ::RoboCompAGMWorldModel::Edge&, const ::Ice::Context&);
    /// \endcond

    void edgesUpdated(const ::RoboCompAGMWorldModel::EdgeSequence& modifications, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        _makePromiseOutgoing<void>(true, this, &AGMExecutiveTopicPrx::_iceI_edgesUpdated, modifications, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto edgesUpdatedAsync(const ::RoboCompAGMWorldModel::EdgeSequence& modifications, const ::Ice::Context& context = ::Ice::noExplicitContext)
        -> decltype(::std::declval<P<void>>().get_future())
    {
        return _makePromiseOutgoing<void, P>(false, this, &AGMExecutiveTopicPrx::_iceI_edgesUpdated, modifications, context);
    }

    ::std::function<void()>
    edgesUpdatedAsync(const ::RoboCompAGMWorldModel::EdgeSequence& modifications,
                      ::std::function<void()> response,
                      ::std::function<void(::std::exception_ptr)> ex = nullptr,
                      ::std::function<void(bool)> sent = nullptr,
                      const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<void>(response, ex, sent, this, &RoboCompAGMExecutiveTopic::AGMExecutiveTopicPrx::_iceI_edgesUpdated, modifications, context);
    }

    /// \cond INTERNAL
    void _iceI_edgesUpdated(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>&, const ::RoboCompAGMWorldModel::EdgeSequence&, const ::Ice::Context&);
    /// \endcond

    void selfEdgeAdded(int nodeid, const ::std::string& edgeType, const ::RoboCompAGMWorldModel::StringDictionary& attributes, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        _makePromiseOutgoing<void>(true, this, &AGMExecutiveTopicPrx::_iceI_selfEdgeAdded, nodeid, edgeType, attributes, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto selfEdgeAddedAsync(int nodeid, const ::std::string& edgeType, const ::RoboCompAGMWorldModel::StringDictionary& attributes, const ::Ice::Context& context = ::Ice::noExplicitContext)
        -> decltype(::std::declval<P<void>>().get_future())
    {
        return _makePromiseOutgoing<void, P>(false, this, &AGMExecutiveTopicPrx::_iceI_selfEdgeAdded, nodeid, edgeType, attributes, context);
    }

    ::std::function<void()>
    selfEdgeAddedAsync(int nodeid, const ::std::string& edgeType, const ::RoboCompAGMWorldModel::StringDictionary& attributes,
                       ::std::function<void()> response,
                       ::std::function<void(::std::exception_ptr)> ex = nullptr,
                       ::std::function<void(bool)> sent = nullptr,
                       const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<void>(response, ex, sent, this, &RoboCompAGMExecutiveTopic::AGMExecutiveTopicPrx::_iceI_selfEdgeAdded, nodeid, edgeType, attributes, context);
    }

    /// \cond INTERNAL
    void _iceI_selfEdgeAdded(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>&, int, const ::std::string&, const ::RoboCompAGMWorldModel::StringDictionary&, const ::Ice::Context&);
    /// \endcond

    void selfEdgeDeleted(int nodeid, const ::std::string& edgeType, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        _makePromiseOutgoing<void>(true, this, &AGMExecutiveTopicPrx::_iceI_selfEdgeDeleted, nodeid, edgeType, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto selfEdgeDeletedAsync(int nodeid, const ::std::string& edgeType, const ::Ice::Context& context = ::Ice::noExplicitContext)
        -> decltype(::std::declval<P<void>>().get_future())
    {
        return _makePromiseOutgoing<void, P>(false, this, &AGMExecutiveTopicPrx::_iceI_selfEdgeDeleted, nodeid, edgeType, context);
    }

    ::std::function<void()>
    selfEdgeDeletedAsync(int nodeid, const ::std::string& edgeType,
                         ::std::function<void()> response,
                         ::std::function<void(::std::exception_ptr)> ex = nullptr,
                         ::std::function<void(bool)> sent = nullptr,
                         const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<void>(response, ex, sent, this, &RoboCompAGMExecutiveTopic::AGMExecutiveTopicPrx::_iceI_selfEdgeDeleted, nodeid, edgeType, context);
    }

    /// \cond INTERNAL
    void _iceI_selfEdgeDeleted(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>&, int, const ::std::string&, const ::Ice::Context&);
    /// \endcond

    void structuralChange(const ::RoboCompAGMWorldModel::World& w, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        _makePromiseOutgoing<void>(true, this, &AGMExecutiveTopicPrx::_iceI_structuralChange, w, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto structuralChangeAsync(const ::RoboCompAGMWorldModel::World& w, const ::Ice::Context& context = ::Ice::noExplicitContext)
        -> decltype(::std::declval<P<void>>().get_future())
    {
        return _makePromiseOutgoing<void, P>(false, this, &AGMExecutiveTopicPrx::_iceI_structuralChange, w, context);
    }

    ::std::function<void()>
    structuralChangeAsync(const ::RoboCompAGMWorldModel::World& w,
                          ::std::function<void()> response,
                          ::std::function<void(::std::exception_ptr)> ex = nullptr,
                          ::std::function<void(bool)> sent = nullptr,
                          const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<void>(response, ex, sent, this, &RoboCompAGMExecutiveTopic::AGMExecutiveTopicPrx::_iceI_structuralChange, w, context);
    }

    /// \cond INTERNAL
    void _iceI_structuralChange(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>&, const ::RoboCompAGMWorldModel::World&, const ::Ice::Context&);
    /// \endcond

    void symbolUpdated(const ::RoboCompAGMWorldModel::Node& modification, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        _makePromiseOutgoing<void>(true, this, &AGMExecutiveTopicPrx::_iceI_symbolUpdated, modification, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto symbolUpdatedAsync(const ::RoboCompAGMWorldModel::Node& modification, const ::Ice::Context& context = ::Ice::noExplicitContext)
        -> decltype(::std::declval<P<void>>().get_future())
    {
        return _makePromiseOutgoing<void, P>(false, this, &AGMExecutiveTopicPrx::_iceI_symbolUpdated, modification, context);
    }

    ::std::function<void()>
    symbolUpdatedAsync(const ::RoboCompAGMWorldModel::Node& modification,
                       ::std::function<void()> response,
                       ::std::function<void(::std::exception_ptr)> ex = nullptr,
                       ::std::function<void(bool)> sent = nullptr,
                       const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<void>(response, ex, sent, this, &RoboCompAGMExecutiveTopic::AGMExecutiveTopicPrx::_iceI_symbolUpdated, modification, context);
    }

    /// \cond INTERNAL
    void _iceI_symbolUpdated(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>&, const ::RoboCompAGMWorldModel::Node&, const ::Ice::Context&);
    /// \endcond

    void symbolsUpdated(const ::RoboCompAGMWorldModel::NodeSequence& modifications, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        _makePromiseOutgoing<void>(true, this, &AGMExecutiveTopicPrx::_iceI_symbolsUpdated, modifications, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto symbolsUpdatedAsync(const ::RoboCompAGMWorldModel::NodeSequence& modifications, const ::Ice::Context& context = ::Ice::noExplicitContext)
        -> decltype(::std::declval<P<void>>().get_future())
    {
        return _makePromiseOutgoing<void, P>(false, this, &AGMExecutiveTopicPrx::_iceI_symbolsUpdated, modifications, context);
    }

    ::std::function<void()>
    symbolsUpdatedAsync(const ::RoboCompAGMWorldModel::NodeSequence& modifications,
                        ::std::function<void()> response,
                        ::std::function<void(::std::exception_ptr)> ex = nullptr,
                        ::std::function<void(bool)> sent = nullptr,
                        const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<void>(response, ex, sent, this, &RoboCompAGMExecutiveTopic::AGMExecutiveTopicPrx::_iceI_symbolsUpdated, modifications, context);
    }

    /// \cond INTERNAL
    void _iceI_symbolsUpdated(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>&, const ::RoboCompAGMWorldModel::NodeSequence&, const ::Ice::Context&);
    /// \endcond

    /**
     * Obtains the Slice type ID of this interface.
     * @return The fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

protected:

    /// \cond INTERNAL
    AGMExecutiveTopicPrx() = default;
    friend ::std::shared_ptr<AGMExecutiveTopicPrx> IceInternal::createProxy<AGMExecutiveTopicPrx>();

    virtual ::std::shared_ptr<::Ice::ObjectPrx> _newInstance() const override;
    /// \endcond
};

}

/// \cond STREAM
namespace Ice
{

}
/// \endcond

/// \cond INTERNAL
namespace RoboCompAGMExecutiveTopic
{

using AGMExecutiveTopicPtr = ::std::shared_ptr<AGMExecutiveTopic>;
using AGMExecutiveTopicPrxPtr = ::std::shared_ptr<AGMExecutiveTopicPrx>;

}
/// \endcond

#else // C++98 mapping

namespace IceProxy
{

namespace RoboCompAGMExecutiveTopic
{

class AGMExecutiveTopic;
/// \cond INTERNAL
void _readProxy(::Ice::InputStream*, ::IceInternal::ProxyHandle< AGMExecutiveTopic>&);
::IceProxy::Ice::Object* upCast(AGMExecutiveTopic*);
/// \endcond

}

}

namespace RoboCompAGMExecutiveTopic
{

class AGMExecutiveTopic;
/// \cond INTERNAL
::Ice::Object* upCast(AGMExecutiveTopic*);
/// \endcond
typedef ::IceInternal::Handle< AGMExecutiveTopic> AGMExecutiveTopicPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic> AGMExecutiveTopicPrx;
typedef AGMExecutiveTopicPrx AGMExecutiveTopicPrxPtr;
/// \cond INTERNAL
void _icePatchObjectPtr(AGMExecutiveTopicPtr&, const ::Ice::ObjectPtr&);
/// \endcond

}

namespace RoboCompAGMExecutiveTopic
{

/**
 * Base class for asynchronous callback wrapper classes used for calls to
 * IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_edgeUpdated.
 * Create a wrapper instance by calling ::RoboCompAGMExecutiveTopic::newCallback_AGMExecutiveTopic_edgeUpdated.
 */
class Callback_AGMExecutiveTopic_edgeUpdated_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_AGMExecutiveTopic_edgeUpdated_Base> Callback_AGMExecutiveTopic_edgeUpdatedPtr;

/**
 * Base class for asynchronous callback wrapper classes used for calls to
 * IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_edgesUpdated.
 * Create a wrapper instance by calling ::RoboCompAGMExecutiveTopic::newCallback_AGMExecutiveTopic_edgesUpdated.
 */
class Callback_AGMExecutiveTopic_edgesUpdated_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_AGMExecutiveTopic_edgesUpdated_Base> Callback_AGMExecutiveTopic_edgesUpdatedPtr;

/**
 * Base class for asynchronous callback wrapper classes used for calls to
 * IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_selfEdgeAdded.
 * Create a wrapper instance by calling ::RoboCompAGMExecutiveTopic::newCallback_AGMExecutiveTopic_selfEdgeAdded.
 */
class Callback_AGMExecutiveTopic_selfEdgeAdded_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_AGMExecutiveTopic_selfEdgeAdded_Base> Callback_AGMExecutiveTopic_selfEdgeAddedPtr;

/**
 * Base class for asynchronous callback wrapper classes used for calls to
 * IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_selfEdgeDeleted.
 * Create a wrapper instance by calling ::RoboCompAGMExecutiveTopic::newCallback_AGMExecutiveTopic_selfEdgeDeleted.
 */
class Callback_AGMExecutiveTopic_selfEdgeDeleted_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_AGMExecutiveTopic_selfEdgeDeleted_Base> Callback_AGMExecutiveTopic_selfEdgeDeletedPtr;

/**
 * Base class for asynchronous callback wrapper classes used for calls to
 * IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_structuralChange.
 * Create a wrapper instance by calling ::RoboCompAGMExecutiveTopic::newCallback_AGMExecutiveTopic_structuralChange.
 */
class Callback_AGMExecutiveTopic_structuralChange_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_AGMExecutiveTopic_structuralChange_Base> Callback_AGMExecutiveTopic_structuralChangePtr;

/**
 * Base class for asynchronous callback wrapper classes used for calls to
 * IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_symbolUpdated.
 * Create a wrapper instance by calling ::RoboCompAGMExecutiveTopic::newCallback_AGMExecutiveTopic_symbolUpdated.
 */
class Callback_AGMExecutiveTopic_symbolUpdated_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_AGMExecutiveTopic_symbolUpdated_Base> Callback_AGMExecutiveTopic_symbolUpdatedPtr;

/**
 * Base class for asynchronous callback wrapper classes used for calls to
 * IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_symbolsUpdated.
 * Create a wrapper instance by calling ::RoboCompAGMExecutiveTopic::newCallback_AGMExecutiveTopic_symbolsUpdated.
 */
class Callback_AGMExecutiveTopic_symbolsUpdated_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_AGMExecutiveTopic_symbolsUpdated_Base> Callback_AGMExecutiveTopic_symbolsUpdatedPtr;

}

namespace IceProxy
{

namespace RoboCompAGMExecutiveTopic
{

class AGMExecutiveTopic : public virtual ::Ice::Proxy<AGMExecutiveTopic, ::IceProxy::Ice::Object>
{
public:

    void edgeUpdated(const ::RoboCompAGMWorldModel::Edge& modification, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        end_edgeUpdated(_iceI_begin_edgeUpdated(modification, context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_edgeUpdated(const ::RoboCompAGMWorldModel::Edge& modification, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_edgeUpdated(modification, context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_edgeUpdated(const ::RoboCompAGMWorldModel::Edge& modification, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_edgeUpdated(modification, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_edgeUpdated(const ::RoboCompAGMWorldModel::Edge& modification, const ::Ice::Context& context, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_edgeUpdated(modification, context, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_edgeUpdated(const ::RoboCompAGMWorldModel::Edge& modification, const ::RoboCompAGMExecutiveTopic::Callback_AGMExecutiveTopic_edgeUpdatedPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_edgeUpdated(modification, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_edgeUpdated(const ::RoboCompAGMWorldModel::Edge& modification, const ::Ice::Context& context, const ::RoboCompAGMExecutiveTopic::Callback_AGMExecutiveTopic_edgeUpdatedPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_edgeUpdated(modification, context, cb, cookie);
    }

    void end_edgeUpdated(const ::Ice::AsyncResultPtr& result);

private:

    ::Ice::AsyncResultPtr _iceI_begin_edgeUpdated(const ::RoboCompAGMWorldModel::Edge&, const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    void edgesUpdated(const ::RoboCompAGMWorldModel::EdgeSequence& modifications, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        end_edgesUpdated(_iceI_begin_edgesUpdated(modifications, context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_edgesUpdated(const ::RoboCompAGMWorldModel::EdgeSequence& modifications, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_edgesUpdated(modifications, context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_edgesUpdated(const ::RoboCompAGMWorldModel::EdgeSequence& modifications, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_edgesUpdated(modifications, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_edgesUpdated(const ::RoboCompAGMWorldModel::EdgeSequence& modifications, const ::Ice::Context& context, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_edgesUpdated(modifications, context, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_edgesUpdated(const ::RoboCompAGMWorldModel::EdgeSequence& modifications, const ::RoboCompAGMExecutiveTopic::Callback_AGMExecutiveTopic_edgesUpdatedPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_edgesUpdated(modifications, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_edgesUpdated(const ::RoboCompAGMWorldModel::EdgeSequence& modifications, const ::Ice::Context& context, const ::RoboCompAGMExecutiveTopic::Callback_AGMExecutiveTopic_edgesUpdatedPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_edgesUpdated(modifications, context, cb, cookie);
    }

    void end_edgesUpdated(const ::Ice::AsyncResultPtr& result);

private:

    ::Ice::AsyncResultPtr _iceI_begin_edgesUpdated(const ::RoboCompAGMWorldModel::EdgeSequence&, const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    void selfEdgeAdded(::Ice::Int nodeid, const ::std::string& edgeType, const ::RoboCompAGMWorldModel::StringDictionary& attributes, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        end_selfEdgeAdded(_iceI_begin_selfEdgeAdded(nodeid, edgeType, attributes, context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_selfEdgeAdded(::Ice::Int nodeid, const ::std::string& edgeType, const ::RoboCompAGMWorldModel::StringDictionary& attributes, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_selfEdgeAdded(nodeid, edgeType, attributes, context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_selfEdgeAdded(::Ice::Int nodeid, const ::std::string& edgeType, const ::RoboCompAGMWorldModel::StringDictionary& attributes, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_selfEdgeAdded(nodeid, edgeType, attributes, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_selfEdgeAdded(::Ice::Int nodeid, const ::std::string& edgeType, const ::RoboCompAGMWorldModel::StringDictionary& attributes, const ::Ice::Context& context, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_selfEdgeAdded(nodeid, edgeType, attributes, context, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_selfEdgeAdded(::Ice::Int nodeid, const ::std::string& edgeType, const ::RoboCompAGMWorldModel::StringDictionary& attributes, const ::RoboCompAGMExecutiveTopic::Callback_AGMExecutiveTopic_selfEdgeAddedPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_selfEdgeAdded(nodeid, edgeType, attributes, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_selfEdgeAdded(::Ice::Int nodeid, const ::std::string& edgeType, const ::RoboCompAGMWorldModel::StringDictionary& attributes, const ::Ice::Context& context, const ::RoboCompAGMExecutiveTopic::Callback_AGMExecutiveTopic_selfEdgeAddedPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_selfEdgeAdded(nodeid, edgeType, attributes, context, cb, cookie);
    }

    void end_selfEdgeAdded(const ::Ice::AsyncResultPtr& result);

private:

    ::Ice::AsyncResultPtr _iceI_begin_selfEdgeAdded(::Ice::Int, const ::std::string&, const ::RoboCompAGMWorldModel::StringDictionary&, const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    void selfEdgeDeleted(::Ice::Int nodeid, const ::std::string& edgeType, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        end_selfEdgeDeleted(_iceI_begin_selfEdgeDeleted(nodeid, edgeType, context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_selfEdgeDeleted(::Ice::Int nodeid, const ::std::string& edgeType, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_selfEdgeDeleted(nodeid, edgeType, context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_selfEdgeDeleted(::Ice::Int nodeid, const ::std::string& edgeType, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_selfEdgeDeleted(nodeid, edgeType, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_selfEdgeDeleted(::Ice::Int nodeid, const ::std::string& edgeType, const ::Ice::Context& context, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_selfEdgeDeleted(nodeid, edgeType, context, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_selfEdgeDeleted(::Ice::Int nodeid, const ::std::string& edgeType, const ::RoboCompAGMExecutiveTopic::Callback_AGMExecutiveTopic_selfEdgeDeletedPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_selfEdgeDeleted(nodeid, edgeType, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_selfEdgeDeleted(::Ice::Int nodeid, const ::std::string& edgeType, const ::Ice::Context& context, const ::RoboCompAGMExecutiveTopic::Callback_AGMExecutiveTopic_selfEdgeDeletedPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_selfEdgeDeleted(nodeid, edgeType, context, cb, cookie);
    }

    void end_selfEdgeDeleted(const ::Ice::AsyncResultPtr& result);

private:

    ::Ice::AsyncResultPtr _iceI_begin_selfEdgeDeleted(::Ice::Int, const ::std::string&, const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    void structuralChange(const ::RoboCompAGMWorldModel::World& w, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        end_structuralChange(_iceI_begin_structuralChange(w, context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_structuralChange(const ::RoboCompAGMWorldModel::World& w, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_structuralChange(w, context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_structuralChange(const ::RoboCompAGMWorldModel::World& w, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_structuralChange(w, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_structuralChange(const ::RoboCompAGMWorldModel::World& w, const ::Ice::Context& context, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_structuralChange(w, context, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_structuralChange(const ::RoboCompAGMWorldModel::World& w, const ::RoboCompAGMExecutiveTopic::Callback_AGMExecutiveTopic_structuralChangePtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_structuralChange(w, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_structuralChange(const ::RoboCompAGMWorldModel::World& w, const ::Ice::Context& context, const ::RoboCompAGMExecutiveTopic::Callback_AGMExecutiveTopic_structuralChangePtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_structuralChange(w, context, cb, cookie);
    }

    void end_structuralChange(const ::Ice::AsyncResultPtr& result);

private:

    ::Ice::AsyncResultPtr _iceI_begin_structuralChange(const ::RoboCompAGMWorldModel::World&, const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    void symbolUpdated(const ::RoboCompAGMWorldModel::Node& modification, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        end_symbolUpdated(_iceI_begin_symbolUpdated(modification, context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_symbolUpdated(const ::RoboCompAGMWorldModel::Node& modification, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_symbolUpdated(modification, context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_symbolUpdated(const ::RoboCompAGMWorldModel::Node& modification, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_symbolUpdated(modification, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_symbolUpdated(const ::RoboCompAGMWorldModel::Node& modification, const ::Ice::Context& context, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_symbolUpdated(modification, context, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_symbolUpdated(const ::RoboCompAGMWorldModel::Node& modification, const ::RoboCompAGMExecutiveTopic::Callback_AGMExecutiveTopic_symbolUpdatedPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_symbolUpdated(modification, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_symbolUpdated(const ::RoboCompAGMWorldModel::Node& modification, const ::Ice::Context& context, const ::RoboCompAGMExecutiveTopic::Callback_AGMExecutiveTopic_symbolUpdatedPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_symbolUpdated(modification, context, cb, cookie);
    }

    void end_symbolUpdated(const ::Ice::AsyncResultPtr& result);

private:

    ::Ice::AsyncResultPtr _iceI_begin_symbolUpdated(const ::RoboCompAGMWorldModel::Node&, const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    void symbolsUpdated(const ::RoboCompAGMWorldModel::NodeSequence& modifications, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        end_symbolsUpdated(_iceI_begin_symbolsUpdated(modifications, context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_symbolsUpdated(const ::RoboCompAGMWorldModel::NodeSequence& modifications, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_symbolsUpdated(modifications, context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_symbolsUpdated(const ::RoboCompAGMWorldModel::NodeSequence& modifications, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_symbolsUpdated(modifications, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_symbolsUpdated(const ::RoboCompAGMWorldModel::NodeSequence& modifications, const ::Ice::Context& context, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_symbolsUpdated(modifications, context, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_symbolsUpdated(const ::RoboCompAGMWorldModel::NodeSequence& modifications, const ::RoboCompAGMExecutiveTopic::Callback_AGMExecutiveTopic_symbolsUpdatedPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_symbolsUpdated(modifications, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_symbolsUpdated(const ::RoboCompAGMWorldModel::NodeSequence& modifications, const ::Ice::Context& context, const ::RoboCompAGMExecutiveTopic::Callback_AGMExecutiveTopic_symbolsUpdatedPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_symbolsUpdated(modifications, context, cb, cookie);
    }

    void end_symbolsUpdated(const ::Ice::AsyncResultPtr& result);

private:

    ::Ice::AsyncResultPtr _iceI_begin_symbolsUpdated(const ::RoboCompAGMWorldModel::NodeSequence&, const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    /**
     * Obtains the Slice type ID corresponding to this interface.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

protected:
    /// \cond INTERNAL

    virtual ::IceProxy::Ice::Object* _newInstance() const;
    /// \endcond
};

}

}

namespace RoboCompAGMExecutiveTopic
{

class AGMExecutiveTopic : public virtual ::Ice::Object
{
public:

    typedef AGMExecutiveTopicPrx ProxyType;
    typedef AGMExecutiveTopicPtr PointerType;

    virtual ~AGMExecutiveTopic();

    /**
     * Determines whether this object supports an interface with the given Slice type ID.
     * @param id The fully-scoped Slice type ID.
     * @param current The Current object for the invocation.
     * @return True if this object supports the interface, false, otherwise.
     */
    virtual bool ice_isA(const ::std::string& id, const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains a list of the Slice type IDs representing the interfaces supported by this object.
     * @param current The Current object for the invocation.
     * @return A list of fully-scoped type IDs.
     */
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains a Slice type ID representing the most-derived interface supported by this object.
     * @param current The Current object for the invocation.
     * @return A fully-scoped type ID.
     */
    virtual const ::std::string& ice_id(const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains the Slice type ID corresponding to this class.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

    virtual void edgeUpdated(const ::RoboCompAGMWorldModel::Edge& modification, const ::Ice::Current& current = ::Ice::emptyCurrent) = 0;
    /// \cond INTERNAL
    bool _iceD_edgeUpdated(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual void edgesUpdated(const ::RoboCompAGMWorldModel::EdgeSequence& modifications, const ::Ice::Current& current = ::Ice::emptyCurrent) = 0;
    /// \cond INTERNAL
    bool _iceD_edgesUpdated(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual void selfEdgeAdded(::Ice::Int nodeid, const ::std::string& edgeType, const ::RoboCompAGMWorldModel::StringDictionary& attributes, const ::Ice::Current& current = ::Ice::emptyCurrent) = 0;
    /// \cond INTERNAL
    bool _iceD_selfEdgeAdded(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual void selfEdgeDeleted(::Ice::Int nodeid, const ::std::string& edgeType, const ::Ice::Current& current = ::Ice::emptyCurrent) = 0;
    /// \cond INTERNAL
    bool _iceD_selfEdgeDeleted(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual void structuralChange(const ::RoboCompAGMWorldModel::World& w, const ::Ice::Current& current = ::Ice::emptyCurrent) = 0;
    /// \cond INTERNAL
    bool _iceD_structuralChange(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual void symbolUpdated(const ::RoboCompAGMWorldModel::Node& modification, const ::Ice::Current& current = ::Ice::emptyCurrent) = 0;
    /// \cond INTERNAL
    bool _iceD_symbolUpdated(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual void symbolsUpdated(const ::RoboCompAGMWorldModel::NodeSequence& modifications, const ::Ice::Current& current = ::Ice::emptyCurrent) = 0;
    /// \cond INTERNAL
    bool _iceD_symbolsUpdated(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    /// \cond INTERNAL
    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

protected:

    /// \cond STREAM
    virtual void _iceWriteImpl(::Ice::OutputStream*) const;
    virtual void _iceReadImpl(::Ice::InputStream*);
    /// \endcond
};

/// \cond INTERNAL
inline bool operator==(const AGMExecutiveTopic& lhs, const AGMExecutiveTopic& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) == static_cast<const ::Ice::Object&>(rhs);
}

inline bool operator<(const AGMExecutiveTopic& lhs, const AGMExecutiveTopic& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) < static_cast<const ::Ice::Object&>(rhs);
}
/// \endcond

}

/// \cond STREAM
namespace Ice
{

}
/// \endcond

namespace RoboCompAGMExecutiveTopic
{

/**
 * Type-safe asynchronous callback wrapper class used for calls to
 * IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_edgeUpdated.
 * Create a wrapper instance by calling ::RoboCompAGMExecutiveTopic::newCallback_AGMExecutiveTopic_edgeUpdated.
 */
template<class T>
class CallbackNC_AGMExecutiveTopic_edgeUpdated : public Callback_AGMExecutiveTopic_edgeUpdated_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_AGMExecutiveTopic_edgeUpdated(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_edgeUpdated.
 */
template<class T> Callback_AGMExecutiveTopic_edgeUpdatedPtr
newCallback_AGMExecutiveTopic_edgeUpdated(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AGMExecutiveTopic_edgeUpdated<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_edgeUpdated.
 */
template<class T> Callback_AGMExecutiveTopic_edgeUpdatedPtr
newCallback_AGMExecutiveTopic_edgeUpdated(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AGMExecutiveTopic_edgeUpdated<T>(instance, 0, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_edgeUpdated.
 */
template<class T> Callback_AGMExecutiveTopic_edgeUpdatedPtr
newCallback_AGMExecutiveTopic_edgeUpdated(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AGMExecutiveTopic_edgeUpdated<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_edgeUpdated.
 */
template<class T> Callback_AGMExecutiveTopic_edgeUpdatedPtr
newCallback_AGMExecutiveTopic_edgeUpdated(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AGMExecutiveTopic_edgeUpdated<T>(instance, 0, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class with cookie support used for calls to
 * IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_edgeUpdated.
 * Create a wrapper instance by calling ::RoboCompAGMExecutiveTopic::newCallback_AGMExecutiveTopic_edgeUpdated.
 */
template<class T, typename CT>
class Callback_AGMExecutiveTopic_edgeUpdated : public Callback_AGMExecutiveTopic_edgeUpdated_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_AGMExecutiveTopic_edgeUpdated(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_edgeUpdated.
 */
template<class T, typename CT> Callback_AGMExecutiveTopic_edgeUpdatedPtr
newCallback_AGMExecutiveTopic_edgeUpdated(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AGMExecutiveTopic_edgeUpdated<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_edgeUpdated.
 */
template<class T, typename CT> Callback_AGMExecutiveTopic_edgeUpdatedPtr
newCallback_AGMExecutiveTopic_edgeUpdated(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AGMExecutiveTopic_edgeUpdated<T, CT>(instance, 0, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_edgeUpdated.
 */
template<class T, typename CT> Callback_AGMExecutiveTopic_edgeUpdatedPtr
newCallback_AGMExecutiveTopic_edgeUpdated(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AGMExecutiveTopic_edgeUpdated<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_edgeUpdated.
 */
template<class T, typename CT> Callback_AGMExecutiveTopic_edgeUpdatedPtr
newCallback_AGMExecutiveTopic_edgeUpdated(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AGMExecutiveTopic_edgeUpdated<T, CT>(instance, 0, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class used for calls to
 * IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_edgesUpdated.
 * Create a wrapper instance by calling ::RoboCompAGMExecutiveTopic::newCallback_AGMExecutiveTopic_edgesUpdated.
 */
template<class T>
class CallbackNC_AGMExecutiveTopic_edgesUpdated : public Callback_AGMExecutiveTopic_edgesUpdated_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_AGMExecutiveTopic_edgesUpdated(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_edgesUpdated.
 */
template<class T> Callback_AGMExecutiveTopic_edgesUpdatedPtr
newCallback_AGMExecutiveTopic_edgesUpdated(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AGMExecutiveTopic_edgesUpdated<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_edgesUpdated.
 */
template<class T> Callback_AGMExecutiveTopic_edgesUpdatedPtr
newCallback_AGMExecutiveTopic_edgesUpdated(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AGMExecutiveTopic_edgesUpdated<T>(instance, 0, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_edgesUpdated.
 */
template<class T> Callback_AGMExecutiveTopic_edgesUpdatedPtr
newCallback_AGMExecutiveTopic_edgesUpdated(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AGMExecutiveTopic_edgesUpdated<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_edgesUpdated.
 */
template<class T> Callback_AGMExecutiveTopic_edgesUpdatedPtr
newCallback_AGMExecutiveTopic_edgesUpdated(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AGMExecutiveTopic_edgesUpdated<T>(instance, 0, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class with cookie support used for calls to
 * IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_edgesUpdated.
 * Create a wrapper instance by calling ::RoboCompAGMExecutiveTopic::newCallback_AGMExecutiveTopic_edgesUpdated.
 */
template<class T, typename CT>
class Callback_AGMExecutiveTopic_edgesUpdated : public Callback_AGMExecutiveTopic_edgesUpdated_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_AGMExecutiveTopic_edgesUpdated(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_edgesUpdated.
 */
template<class T, typename CT> Callback_AGMExecutiveTopic_edgesUpdatedPtr
newCallback_AGMExecutiveTopic_edgesUpdated(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AGMExecutiveTopic_edgesUpdated<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_edgesUpdated.
 */
template<class T, typename CT> Callback_AGMExecutiveTopic_edgesUpdatedPtr
newCallback_AGMExecutiveTopic_edgesUpdated(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AGMExecutiveTopic_edgesUpdated<T, CT>(instance, 0, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_edgesUpdated.
 */
template<class T, typename CT> Callback_AGMExecutiveTopic_edgesUpdatedPtr
newCallback_AGMExecutiveTopic_edgesUpdated(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AGMExecutiveTopic_edgesUpdated<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_edgesUpdated.
 */
template<class T, typename CT> Callback_AGMExecutiveTopic_edgesUpdatedPtr
newCallback_AGMExecutiveTopic_edgesUpdated(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AGMExecutiveTopic_edgesUpdated<T, CT>(instance, 0, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class used for calls to
 * IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_selfEdgeAdded.
 * Create a wrapper instance by calling ::RoboCompAGMExecutiveTopic::newCallback_AGMExecutiveTopic_selfEdgeAdded.
 */
template<class T>
class CallbackNC_AGMExecutiveTopic_selfEdgeAdded : public Callback_AGMExecutiveTopic_selfEdgeAdded_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_AGMExecutiveTopic_selfEdgeAdded(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_selfEdgeAdded.
 */
template<class T> Callback_AGMExecutiveTopic_selfEdgeAddedPtr
newCallback_AGMExecutiveTopic_selfEdgeAdded(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AGMExecutiveTopic_selfEdgeAdded<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_selfEdgeAdded.
 */
template<class T> Callback_AGMExecutiveTopic_selfEdgeAddedPtr
newCallback_AGMExecutiveTopic_selfEdgeAdded(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AGMExecutiveTopic_selfEdgeAdded<T>(instance, 0, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_selfEdgeAdded.
 */
template<class T> Callback_AGMExecutiveTopic_selfEdgeAddedPtr
newCallback_AGMExecutiveTopic_selfEdgeAdded(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AGMExecutiveTopic_selfEdgeAdded<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_selfEdgeAdded.
 */
template<class T> Callback_AGMExecutiveTopic_selfEdgeAddedPtr
newCallback_AGMExecutiveTopic_selfEdgeAdded(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AGMExecutiveTopic_selfEdgeAdded<T>(instance, 0, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class with cookie support used for calls to
 * IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_selfEdgeAdded.
 * Create a wrapper instance by calling ::RoboCompAGMExecutiveTopic::newCallback_AGMExecutiveTopic_selfEdgeAdded.
 */
template<class T, typename CT>
class Callback_AGMExecutiveTopic_selfEdgeAdded : public Callback_AGMExecutiveTopic_selfEdgeAdded_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_AGMExecutiveTopic_selfEdgeAdded(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_selfEdgeAdded.
 */
template<class T, typename CT> Callback_AGMExecutiveTopic_selfEdgeAddedPtr
newCallback_AGMExecutiveTopic_selfEdgeAdded(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AGMExecutiveTopic_selfEdgeAdded<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_selfEdgeAdded.
 */
template<class T, typename CT> Callback_AGMExecutiveTopic_selfEdgeAddedPtr
newCallback_AGMExecutiveTopic_selfEdgeAdded(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AGMExecutiveTopic_selfEdgeAdded<T, CT>(instance, 0, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_selfEdgeAdded.
 */
template<class T, typename CT> Callback_AGMExecutiveTopic_selfEdgeAddedPtr
newCallback_AGMExecutiveTopic_selfEdgeAdded(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AGMExecutiveTopic_selfEdgeAdded<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_selfEdgeAdded.
 */
template<class T, typename CT> Callback_AGMExecutiveTopic_selfEdgeAddedPtr
newCallback_AGMExecutiveTopic_selfEdgeAdded(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AGMExecutiveTopic_selfEdgeAdded<T, CT>(instance, 0, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class used for calls to
 * IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_selfEdgeDeleted.
 * Create a wrapper instance by calling ::RoboCompAGMExecutiveTopic::newCallback_AGMExecutiveTopic_selfEdgeDeleted.
 */
template<class T>
class CallbackNC_AGMExecutiveTopic_selfEdgeDeleted : public Callback_AGMExecutiveTopic_selfEdgeDeleted_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_AGMExecutiveTopic_selfEdgeDeleted(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_selfEdgeDeleted.
 */
template<class T> Callback_AGMExecutiveTopic_selfEdgeDeletedPtr
newCallback_AGMExecutiveTopic_selfEdgeDeleted(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AGMExecutiveTopic_selfEdgeDeleted<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_selfEdgeDeleted.
 */
template<class T> Callback_AGMExecutiveTopic_selfEdgeDeletedPtr
newCallback_AGMExecutiveTopic_selfEdgeDeleted(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AGMExecutiveTopic_selfEdgeDeleted<T>(instance, 0, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_selfEdgeDeleted.
 */
template<class T> Callback_AGMExecutiveTopic_selfEdgeDeletedPtr
newCallback_AGMExecutiveTopic_selfEdgeDeleted(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AGMExecutiveTopic_selfEdgeDeleted<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_selfEdgeDeleted.
 */
template<class T> Callback_AGMExecutiveTopic_selfEdgeDeletedPtr
newCallback_AGMExecutiveTopic_selfEdgeDeleted(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AGMExecutiveTopic_selfEdgeDeleted<T>(instance, 0, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class with cookie support used for calls to
 * IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_selfEdgeDeleted.
 * Create a wrapper instance by calling ::RoboCompAGMExecutiveTopic::newCallback_AGMExecutiveTopic_selfEdgeDeleted.
 */
template<class T, typename CT>
class Callback_AGMExecutiveTopic_selfEdgeDeleted : public Callback_AGMExecutiveTopic_selfEdgeDeleted_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_AGMExecutiveTopic_selfEdgeDeleted(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_selfEdgeDeleted.
 */
template<class T, typename CT> Callback_AGMExecutiveTopic_selfEdgeDeletedPtr
newCallback_AGMExecutiveTopic_selfEdgeDeleted(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AGMExecutiveTopic_selfEdgeDeleted<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_selfEdgeDeleted.
 */
template<class T, typename CT> Callback_AGMExecutiveTopic_selfEdgeDeletedPtr
newCallback_AGMExecutiveTopic_selfEdgeDeleted(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AGMExecutiveTopic_selfEdgeDeleted<T, CT>(instance, 0, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_selfEdgeDeleted.
 */
template<class T, typename CT> Callback_AGMExecutiveTopic_selfEdgeDeletedPtr
newCallback_AGMExecutiveTopic_selfEdgeDeleted(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AGMExecutiveTopic_selfEdgeDeleted<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_selfEdgeDeleted.
 */
template<class T, typename CT> Callback_AGMExecutiveTopic_selfEdgeDeletedPtr
newCallback_AGMExecutiveTopic_selfEdgeDeleted(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AGMExecutiveTopic_selfEdgeDeleted<T, CT>(instance, 0, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class used for calls to
 * IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_structuralChange.
 * Create a wrapper instance by calling ::RoboCompAGMExecutiveTopic::newCallback_AGMExecutiveTopic_structuralChange.
 */
template<class T>
class CallbackNC_AGMExecutiveTopic_structuralChange : public Callback_AGMExecutiveTopic_structuralChange_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_AGMExecutiveTopic_structuralChange(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_structuralChange.
 */
template<class T> Callback_AGMExecutiveTopic_structuralChangePtr
newCallback_AGMExecutiveTopic_structuralChange(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AGMExecutiveTopic_structuralChange<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_structuralChange.
 */
template<class T> Callback_AGMExecutiveTopic_structuralChangePtr
newCallback_AGMExecutiveTopic_structuralChange(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AGMExecutiveTopic_structuralChange<T>(instance, 0, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_structuralChange.
 */
template<class T> Callback_AGMExecutiveTopic_structuralChangePtr
newCallback_AGMExecutiveTopic_structuralChange(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AGMExecutiveTopic_structuralChange<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_structuralChange.
 */
template<class T> Callback_AGMExecutiveTopic_structuralChangePtr
newCallback_AGMExecutiveTopic_structuralChange(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AGMExecutiveTopic_structuralChange<T>(instance, 0, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class with cookie support used for calls to
 * IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_structuralChange.
 * Create a wrapper instance by calling ::RoboCompAGMExecutiveTopic::newCallback_AGMExecutiveTopic_structuralChange.
 */
template<class T, typename CT>
class Callback_AGMExecutiveTopic_structuralChange : public Callback_AGMExecutiveTopic_structuralChange_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_AGMExecutiveTopic_structuralChange(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_structuralChange.
 */
template<class T, typename CT> Callback_AGMExecutiveTopic_structuralChangePtr
newCallback_AGMExecutiveTopic_structuralChange(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AGMExecutiveTopic_structuralChange<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_structuralChange.
 */
template<class T, typename CT> Callback_AGMExecutiveTopic_structuralChangePtr
newCallback_AGMExecutiveTopic_structuralChange(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AGMExecutiveTopic_structuralChange<T, CT>(instance, 0, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_structuralChange.
 */
template<class T, typename CT> Callback_AGMExecutiveTopic_structuralChangePtr
newCallback_AGMExecutiveTopic_structuralChange(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AGMExecutiveTopic_structuralChange<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_structuralChange.
 */
template<class T, typename CT> Callback_AGMExecutiveTopic_structuralChangePtr
newCallback_AGMExecutiveTopic_structuralChange(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AGMExecutiveTopic_structuralChange<T, CT>(instance, 0, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class used for calls to
 * IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_symbolUpdated.
 * Create a wrapper instance by calling ::RoboCompAGMExecutiveTopic::newCallback_AGMExecutiveTopic_symbolUpdated.
 */
template<class T>
class CallbackNC_AGMExecutiveTopic_symbolUpdated : public Callback_AGMExecutiveTopic_symbolUpdated_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_AGMExecutiveTopic_symbolUpdated(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_symbolUpdated.
 */
template<class T> Callback_AGMExecutiveTopic_symbolUpdatedPtr
newCallback_AGMExecutiveTopic_symbolUpdated(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AGMExecutiveTopic_symbolUpdated<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_symbolUpdated.
 */
template<class T> Callback_AGMExecutiveTopic_symbolUpdatedPtr
newCallback_AGMExecutiveTopic_symbolUpdated(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AGMExecutiveTopic_symbolUpdated<T>(instance, 0, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_symbolUpdated.
 */
template<class T> Callback_AGMExecutiveTopic_symbolUpdatedPtr
newCallback_AGMExecutiveTopic_symbolUpdated(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AGMExecutiveTopic_symbolUpdated<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_symbolUpdated.
 */
template<class T> Callback_AGMExecutiveTopic_symbolUpdatedPtr
newCallback_AGMExecutiveTopic_symbolUpdated(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AGMExecutiveTopic_symbolUpdated<T>(instance, 0, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class with cookie support used for calls to
 * IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_symbolUpdated.
 * Create a wrapper instance by calling ::RoboCompAGMExecutiveTopic::newCallback_AGMExecutiveTopic_symbolUpdated.
 */
template<class T, typename CT>
class Callback_AGMExecutiveTopic_symbolUpdated : public Callback_AGMExecutiveTopic_symbolUpdated_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_AGMExecutiveTopic_symbolUpdated(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_symbolUpdated.
 */
template<class T, typename CT> Callback_AGMExecutiveTopic_symbolUpdatedPtr
newCallback_AGMExecutiveTopic_symbolUpdated(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AGMExecutiveTopic_symbolUpdated<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_symbolUpdated.
 */
template<class T, typename CT> Callback_AGMExecutiveTopic_symbolUpdatedPtr
newCallback_AGMExecutiveTopic_symbolUpdated(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AGMExecutiveTopic_symbolUpdated<T, CT>(instance, 0, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_symbolUpdated.
 */
template<class T, typename CT> Callback_AGMExecutiveTopic_symbolUpdatedPtr
newCallback_AGMExecutiveTopic_symbolUpdated(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AGMExecutiveTopic_symbolUpdated<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_symbolUpdated.
 */
template<class T, typename CT> Callback_AGMExecutiveTopic_symbolUpdatedPtr
newCallback_AGMExecutiveTopic_symbolUpdated(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AGMExecutiveTopic_symbolUpdated<T, CT>(instance, 0, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class used for calls to
 * IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_symbolsUpdated.
 * Create a wrapper instance by calling ::RoboCompAGMExecutiveTopic::newCallback_AGMExecutiveTopic_symbolsUpdated.
 */
template<class T>
class CallbackNC_AGMExecutiveTopic_symbolsUpdated : public Callback_AGMExecutiveTopic_symbolsUpdated_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_AGMExecutiveTopic_symbolsUpdated(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_symbolsUpdated.
 */
template<class T> Callback_AGMExecutiveTopic_symbolsUpdatedPtr
newCallback_AGMExecutiveTopic_symbolsUpdated(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AGMExecutiveTopic_symbolsUpdated<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_symbolsUpdated.
 */
template<class T> Callback_AGMExecutiveTopic_symbolsUpdatedPtr
newCallback_AGMExecutiveTopic_symbolsUpdated(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AGMExecutiveTopic_symbolsUpdated<T>(instance, 0, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_symbolsUpdated.
 */
template<class T> Callback_AGMExecutiveTopic_symbolsUpdatedPtr
newCallback_AGMExecutiveTopic_symbolsUpdated(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AGMExecutiveTopic_symbolsUpdated<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_symbolsUpdated.
 */
template<class T> Callback_AGMExecutiveTopic_symbolsUpdatedPtr
newCallback_AGMExecutiveTopic_symbolsUpdated(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AGMExecutiveTopic_symbolsUpdated<T>(instance, 0, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class with cookie support used for calls to
 * IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_symbolsUpdated.
 * Create a wrapper instance by calling ::RoboCompAGMExecutiveTopic::newCallback_AGMExecutiveTopic_symbolsUpdated.
 */
template<class T, typename CT>
class Callback_AGMExecutiveTopic_symbolsUpdated : public Callback_AGMExecutiveTopic_symbolsUpdated_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_AGMExecutiveTopic_symbolsUpdated(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_symbolsUpdated.
 */
template<class T, typename CT> Callback_AGMExecutiveTopic_symbolsUpdatedPtr
newCallback_AGMExecutiveTopic_symbolsUpdated(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AGMExecutiveTopic_symbolsUpdated<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_symbolsUpdated.
 */
template<class T, typename CT> Callback_AGMExecutiveTopic_symbolsUpdatedPtr
newCallback_AGMExecutiveTopic_symbolsUpdated(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AGMExecutiveTopic_symbolsUpdated<T, CT>(instance, 0, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_symbolsUpdated.
 */
template<class T, typename CT> Callback_AGMExecutiveTopic_symbolsUpdatedPtr
newCallback_AGMExecutiveTopic_symbolsUpdated(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AGMExecutiveTopic_symbolsUpdated<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompAGMExecutiveTopic::AGMExecutiveTopic::begin_symbolsUpdated.
 */
template<class T, typename CT> Callback_AGMExecutiveTopic_symbolsUpdatedPtr
newCallback_AGMExecutiveTopic_symbolsUpdated(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AGMExecutiveTopic_symbolsUpdated<T, CT>(instance, 0, excb, sentcb);
}

}

#endif

#include <IceUtil/PopDisableWarnings.h>
#endif
