# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainUI.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *


class Ui_guiDlg(object):
    def setupUi(self, guiDlg):
        if guiDlg.objectName():
            guiDlg.setObjectName(u"guiDlg")
        guiDlg.resize(649, 339)
        self.label_9 = QLabel(guiDlg)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(40, 0, 151, 21))
        self.label_22 = QLabel(guiDlg)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(10, 30, 21, 31))
        self.pushButton_14 = QPushButton(guiDlg)
        self.pushButton_14.setObjectName(u"pushButton_14")
        self.pushButton_14.setGeometry(QRect(146, 30, 101, 23))
        self.line_5 = QFrame(guiDlg)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(246, 2, 20, 91))
        self.line_5.setFrameShape(QFrame.VLine)
        self.line_5.setFrameShadow(QFrame.Sunken)
        self.label_24 = QLabel(guiDlg)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(306, 0, 151, 21))
        self.pushButton_10 = QPushButton(guiDlg)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setGeometry(QRect(266, 60, 91, 23))
        self.pushButton_11 = QPushButton(guiDlg)
        self.pushButton_11.setObjectName(u"pushButton_11")
        self.pushButton_11.setGeometry(QRect(366, 60, 91, 23))
        self.comboBox_3 = QComboBox(guiDlg)
        self.comboBox_3.setObjectName(u"comboBox_3")
        self.comboBox_3.setGeometry(QRect(266, 30, 191, 22))
        self.label = QLabel(guiDlg)
        self.label.setObjectName(u"label")
        self.label.setEnabled(True)
        self.label.setGeometry(QRect(40, 62, 271, 17))
        font = QFont()
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setInputMethodHints(Qt.ImhNone)
        self.dateEdit = QDateEdit(guiDlg)
        self.dateEdit.setObjectName(u"dateEdit")
        self.dateEdit.setGeometry(QRect(36, 28, 93, 26))
        self.groupBox = QGroupBox(guiDlg)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(6, 102, 621, 191))
        self.label_11 = QLabel(self.groupBox)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(198, 56, 17, 21))
        self.label_30 = QLabel(self.groupBox)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(6, 24, 131, 21))
        self.label_12 = QLabel(self.groupBox)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(164, 118, 59, 21))
        self.label_13 = QLabel(self.groupBox)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(362, 52, 57, 21))
        self.label_16 = QLabel(self.groupBox)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(198, 28, 131, 21))
        self.pushButton_4 = QPushButton(self.groupBox)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(362, 104, 91, 23))
        self.label_17 = QLabel(self.groupBox)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(392, 24, 131, 21))
        self.progressBar = QProgressBar(self.groupBox)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(462, 54, 118, 23))
        self.progressBar.setValue(24)
        self.pushButton_5 = QPushButton(self.groupBox)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(478, 106, 105, 23))
        self.graphicsView_3 = QGraphicsView(self.groupBox)
        self.graphicsView_3.setObjectName(u"graphicsView_3")
        self.graphicsView_3.setGeometry(QRect(6, 54, 141, 91))
        self.label_15 = QLabel(self.groupBox)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(196, 88, 19, 21))
        self.pushButton_6 = QPushButton(self.groupBox)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(364, 148, 89, 23))
        self.pushButton_7 = QPushButton(self.groupBox)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(478, 150, 107, 23))
        self.lineEdit = QLineEdit(self.groupBox)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(224, 56, 113, 25))
        self.lineEdit_2 = QLineEdit(self.groupBox)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(224, 88, 113, 25))
        self.lineEdit_3 = QLineEdit(self.groupBox)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(224, 118, 113, 25))
        self.pushButton_8 = QPushButton(self.groupBox)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(226, 148, 89, 23))
        self.pushButton_9 = QPushButton(self.groupBox)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(6, 148, 179, 23))
        self.pushButton_9.setStyleSheet(u"background-color: rgb(239, 41, 41);")
        self.line_7 = QFrame(guiDlg)
        self.line_7.setObjectName(u"line_7")
        self.line_7.setGeometry(QRect(-2, 88, 921, 21))
        self.line_7.setFrameShape(QFrame.HLine)
        self.line_7.setFrameShadow(QFrame.Sunken)

        self.retranslateUi(guiDlg)

        QMetaObject.connectSlotsByName(guiDlg)
    # setupUi

    def retranslateUi(self, guiDlg):
        guiDlg.setWindowTitle(QCoreApplication.translate("guiDlg", u"humanObserverAgent_GUI", None))
        self.label_9.setText(QCoreApplication.translate("guiDlg", u"<html><head/><body><p><span style=\" font-weight:600; color:#054e27;\">Date</span></p></body></html>", None))
        self.label_22.setText(QCoreApplication.translate("guiDlg", u"<html><head/><body><p><img src=\":/GUI/Icons/calendar.png\" /></p></body></html>", None))
        self.pushButton_14.setText(QCoreApplication.translate("guiDlg", u"View agenda", None))
        self.label_24.setText(QCoreApplication.translate("guiDlg", u"<html><head/><body><p><span style=\" font-weight:600; color:#054e27;\">Activity agenda</span></p></body></html>", None))
        self.pushButton_10.setText(QCoreApplication.translate("guiDlg", u"New activity", None))
        self.pushButton_11.setText(QCoreApplication.translate("guiDlg", u"Set activity", None))
        self.label.setText(QCoreApplication.translate("guiDlg", u"Loading", None))
        self.groupBox.setTitle(QCoreApplication.translate("guiDlg", u"Robot navigation and control", None))
        self.label_11.setText(QCoreApplication.translate("guiDlg", u"x", None))
        self.label_30.setText(QCoreApplication.translate("guiDlg", u"Trajectory viewer", None))
        self.label_12.setText(QCoreApplication.translate("guiDlg", u"heading", None))
        self.label_13.setText(QCoreApplication.translate("guiDlg", u"Battery", None))
        self.label_16.setText(QCoreApplication.translate("guiDlg", u"Go to", None))
        self.pushButton_4.setText(QCoreApplication.translate("guiDlg", u"Stop robot", None))
        self.label_17.setText(QCoreApplication.translate("guiDlg", u"Monitoring", None))
        self.pushButton_5.setText(QCoreApplication.translate("guiDlg", u"Reset robot", None))
        self.label_15.setText(QCoreApplication.translate("guiDlg", u"z", None))
        self.pushButton_6.setText(QCoreApplication.translate("guiDlg", u"View Laser", None))
        self.pushButton_7.setText(QCoreApplication.translate("guiDlg", u"View Camera", None))
        self.lineEdit.setText(QCoreApplication.translate("guiDlg", u"0", None))
        self.lineEdit_2.setText(QCoreApplication.translate("guiDlg", u"0", None))
        self.lineEdit_3.setText(QCoreApplication.translate("guiDlg", u"0", None))
        self.pushButton_8.setText(QCoreApplication.translate("guiDlg", u"GO", None))
        self.pushButton_9.setText(QCoreApplication.translate("guiDlg", u"Keyboard Control Off", None))
    # retranslateUi

